Add accessibility linting
FordLabs/PeopleMover pull request #306
Opened 2020-08-19 20:59 UTC by alexwojtala

## Todo
- [x] Add accessibility check to the linter
- [ ] Fix commented out tests
- [ ] Get rid of autofocus from person and product forms (discuss)
- [ ] Get rid of autofocus from base modal class (discuss)
- [ ] Submit assignment form using enter in an accessible way

2020-08-20 13:37 UTC, RandomAshes commented on ui/src/tests/People.test.tsx
> +    // it('opens PersonForm component in editing mode when hambaga icon is clicked', async () => {
Instead of commenting these out, can we just put an x before the it statement so that it at least tells you that there are tests that were ignored?

2020-09-25 17:18 UTC, egriff38ford commented on ui/src/Assignments/AssignmentForm.tsx
> +                role="presentation"
Let's understand why this is here

2020-09-25 17:24 UTC, egriff38ford commented on ui/src/Products/ProductCard.tsx
> +                                        })}
Let's pull these into a single function

2020-09-25 17:25 UTC, egriff38ford commented on ui/src/ReusableComponents/AccountDropdown.tsx
> +                        onKeyDown={() => setCurrentModal({modal: AvailableModals.EDIT_CONTRIBUTORS})}>
let's pull these into a single function if we can

2020-09-25 17:29 UTC, egriff38ford requested changes
Some nits for removing duplication and accidentally commented code

2020-09-25 17:29 UTC, egriff38ford commented on ui/src/ReusableComponents/AccountDropdown.tsx
> +                        onKeyDown={async () => { await ReportClient.getReportsWithNames(currentSpace.name, currentSpace.uuid!!, viewingDate); } }>
let's pull these into a single function if we can

2020-09-25 17:29 UTC, egriff38ford commented on ui/src/tests/Product.test.tsx
> +            // expect(app.queryByLabelText('Name')).toHaveFocus();
remove?

2020-09-25 17:29 UTC, egriff38ford commented on ui/src/Products/ProductCard.tsx
> +                                        })}
let's pull these into a single function if we can

2020-09-25 18:03 UTC, LowBudgetMan commented on ui/src/tests/Product.test.tsx
> +            // expect(app.queryByLabelText('Name')).toHaveFocus();
I agree. No commented out tests

2020-09-25 18:22 UTC, LowBudgetMan requested changes
Investigate onKeyDown and make sure it doesn't happen for every button pressed.

2020-09-25 18:22 UTC, LowBudgetMan commented on ui/src/Assignments/AssignmentCard.tsx
> +                onKeyDown={toggleEditMenu}>
Does this mean any key will open the menu?

2020-09-25 18:22 UTC, LowBudgetMan commented on ui/src/Assignments/AssignmentCard.tsx
> +                onKeyDown={toggleEditMenu}>
If so, I'm rejecting till we make it a specific key. Seems to happen in other places too.

2020-09-28 16:07 UTC, willot requested changes

2020-09-28 16:07 UTC, willot commented on ui/src/SpaceDashboard/SpaceDashboardTile.tsx
> +    function handleKeyDownForOpenSpace(event: React.KeyboardEvent): void {
These 2 functions do excatly the same thing. One with a more generic name should do the trick

2020-09-28 19:00 UTC, egriff38ford approved these changes
LGTU

2020-09-28 19:03 UTC, LowBudgetMan approved these changes

2020-09-28 19:03 UTC, willot approved these changes

2020-09-28 19:04 UTC, merged