My Roles Call-To-Action
FordLabs/PeopleMover pull request #458
Opened 2020-10-12 18:30 UTC by michaelrygiel

## Issue
Resolves #425 

## What was done
- [x] Added edit and delete icons
- [x] Changed styling to match figma design

## How to test
1. Go to my roles modal and see updated edit and delete features for roles

Feature URL: https://featurebranchui.apps.pd01i.edc1.cf.ford.com/

2020-10-12 18:44 UTC, willot commented on ui/src/Traits/MyTraits.scss
> +
remove crazy line and empty lines

2020-10-12 19:09 UTC, willot submitted a review, later dismissed
it works

2020-10-12 19:34 UTC, sabdul14 submitted a review, later dismissed

2020-10-12 19:55 UTC, smle225 requested changes
- Add top paddings on both icons that way they are vertically centered

2020-10-12 20:40 UTC, smle225 requested changes
Both icon for edit and trash can on My Tags modal are not aligned with you hit edit. Both icons for edit and trashcan are skewed to left. Let me know when you need elaboration

2020-10-13 13:43 UTC, RandomAshes commented on ui/src/Traits/MyTraits.tsx
> +        const testIdTraitName = traitName.replace(' ', '');
We created this method for test id's to format them if they have a name value in them: https://github.com/FordLabs/PeopleMover/blob/stage/ui/src/tests/TestUtils.tsx#L43

The format then ends up being `yourPrefix__random_name`

Please use that to parse the data test id's :)

2020-10-13 15:52 UTC, merged