Change verbage to create tags in dropdown and fix focus state styling
FordLabs/PeopleMover pull request #602
Opened 2021-01-06 19:11 UTC by egriff38ford

Co-authored-by: Elise Griffiths <egriff38@ford.com>
Co-authored-by: Alex Wojtala <alexwojtala@gmail.com>

## Issue
Resolves #80 

## What was done
- [x] Fixed focus state styling so that it is obvious what will be created when the user presses enter on a dropdown
- [x] Changed verbage back to 'Create "x"' for the create option on a dropdown

## How to test
1. Create or edit a person, or a product
2. Open a dropdown for role and/or location and/or product tag
3. See that when there are options while typing (partial matches), the highlighted option is obvious. 
4. Use arrow keys to choose whichever option you like

### FOR DEVS
Feature URL: See feature branch

### FOR APPROVAL
Approval URL: See Approval branch

2021-01-06 19:27 UTC, smle225 approved these changes

2021-01-06 19:34 UTC, dulcimerist commented on ui/src/tests/Product.test.tsx
> +                    createOptionText: 'Create "Fin Tech"',
Why use the TestUtils.expectedCreateOptionText function in the previous test (line 285 in this PR), but not here?

2021-01-06 19:36 UTC, dulcimerist requested changes
Some inconsistent usage of the new TestUtils function you introduced in this PR - see comments

2021-01-07 14:36 UTC, alexwojtala approved these changes

2021-01-07 14:46 UTC, smle225 approved these changes
Wooohoo!

2021-01-07 15:14 UTC, merged