101 remove editor access
FordLabs/PeopleMover pull request #647
Opened 2021-02-23 18:40 UTC by jwcherney

## Issue
Resolves 101 

## What was done
- [x] Add removeUser from UserSpaceMapping on backend
- [x] Add remove user capability on frontend 

## How to test
1. Open space
2. Change address, appending `#perm` to end of address to activate feature flag
3. Invite a user to the space
4. Go back to invite user to space. The user should appear. 
5. On the user's permission, open the submenu. Editor should be checked. Clicking on it does nothing (closes submenu)
6. On the user's permission, open the submenu. Remove should be selectable. Clicking on it removes the user from the space.

## Accessiblity Criteria

- [ ] Text and background color meets a minimum color contrast ratio of 4.5:1
- [ ] All non-text content (e.g. images, icon) has alt text
- [ ] Web page includes appropriate headings to communicate structure/hierarchy (h1>h2>h3)
- [x] All functionality is available to a keyboard
  - [ ] Focus styles are highly visible 
  - [ ] Tab order is logical and aligns with the visual order 
- [ ] Voice over is understandable and logical
  - [ ] Aria labels are added to elements with no visible text 
  - [ ] Decorative elements (e.g. non-informative icons) are hidden from screen readers  
- [ ] Form fields have appropriately coded labels that are visible during input 
- [ ] Links are visually identifiable and have a clear focus and active state

2021-02-23 19:47 UTC, jodee requested changes
Focus state was not initially present on Edit options until I refreshed page.

VoiceOver does not indicate the edit drop down option names, just that it is a clickable text list. "Clickable text list to remove or change role, 2 items (Editor or Remove)"

Also noticed that Invite link is not active unless "@ford.com" is appended to CDSID. Is this correct?

2021-02-24 15:16 UTC, jwcherney commented
We haven't been able to reproduce the focus state issue. We believe it was just a refresh issue. 

We fixed the VoiceOver so that it reads the 'Editor' on the select. 

For the edit field, the Invite button doesn't go active until a valid email address is in the text field. This is per the code. The placeholder text in the text field isn't quite correct, but is what was in the design. We can change that if necessary.

2021-02-24 18:04 UTC, jwcherney commented
I modified the text in the placeholder field to match what is currently in Prod ("cdsid@ford.com, cdsid@ford.com")

2021-02-24 18:25 UTC, willot approved these changes

2021-02-24 19:01 UTC, merged